# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(00000E)
$foreground = rgb(F3D2E2)
$color0 = rgb(00000E)
$color1 = rgb(1B2246)
$color2 = rgb(242549)
$color3 = rgb(614063)
$color4 = rgb(72406C)
$color5 = rgb(9E5A7D)
$color6 = rgb(A75E80)
$color7 = rgb(E6B6CD)
$color8 = rgb(A17F8F)
$color9 = rgb(242D5D)
$color10 = rgb(303262)
$color11 = rgb(815584)
$color12 = rgb(985590)
$color13 = rgb(D278A6)
$color14 = rgb(DE7DAB)
$color15 = rgb(E6B6CD)
