use_nerdfont = true
initial_screen = "queue"
volnorm = true

[keybindings]
"Esc" = "back"
"Ctrl+d" = "move pagedown .5"
"Ctrl+u" = "move pageup .5"
"Space" = "playpause"

# Gruvbox dark, by Dawid Kurek
[theme]
background = "default"
primary = "#a89984"
secondary = "#928374"
title = "#8ec07c"
playing = "#689d6a"
playing_bg = "#383838"
playing_selected = "#ebdbb2"
highlight = "#d5c4a1"
highlight_bg = "#484848"
error = "#fbf1c7"
error_bg = "#cc241d"
statusbar_progress = "#458588"
statusbar_bg = "#282828"
statusbar = "#98971a"
cmdline = "#d5c4a1"
cmdline_bg = "#383838"
search_match = "#fabd2f"
