theme = "default"
tracks_playback_limit = 100
play_icon = "󰐊 "
pause_icon = "󰏤 "
liked_icon = "♥"
playback_window_position = "Bottom"
progress_bar_type = "Line"
ap_port = 8012
proxy = "localhost"
client_id = "28b72eeb7a1c4a12aadbf3a5b18e1e0a"

[device]
name = "spotify-player"
device_type = "computer"
volume = 90
bitrate = 320
audio_cache = true
normalization = true
autoplay = true
